[2024-07-14T07:17:48.968+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T07:17:49.005+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-07-14T07:17:47.234625+00:00 [queued]>
[2024-07-14T07:17:49.015+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-07-14T07:17:47.234625+00:00 [queued]>
[2024-07-14T07:17:49.017+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-14T07:17:49.034+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-07-14 07:17:47.234625+00:00
[2024-07-14T07:17:49.044+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=919) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T07:17:49.046+0000] {standard_task_runner.py:63} INFO - Started process 921 to run task
[2024-07-14T07:17:49.046+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-07-14T07:17:47.234625+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/python_dag.py', '--cfg-path', '/tmp/tmpctkbdz17']
[2024-07-14T07:17:49.049+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask reddit_extraction
[2024-07-14T07:17:49.104+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-07-14T07:17:47.234625+00:00 [running]> on host 12ac62825425
[2024-07-14T07:17:49.212+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ademola Balogun' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T07:17:47.234625+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-14T07:17:47.234625+00:00'
[2024-07-14T07:17:49.213+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T07:17:49.228+0000] {logging_mixin.py:188} INFO - Connected to reddit
[2024-07-14T07:17:49.791+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T07:17:49.793+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 11, in reddit_pipeline
    posts = extract_posts(instance, subreddit, time_filter, limit)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etls/reddit_etl.py", line 29, in extract_posts
    post = {key: post_dict[key] for key in POST_FIELDS}
                 ~~~~~~~~~^^^^^
KeyError: 'edit'
[2024-07-14T07:17:49.808+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, run_id=manual__2024-07-14T07:17:47.234625+00:00, execution_date=20240714T071747, start_date=20240714T071749, end_date=20240714T071749
[2024-07-14T07:17:49.820+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task reddit_extraction ('edit'; 921)
[2024-07-14T07:17:49.862+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-14T07:17:49.881+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T07:17:49.882+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
