[2024-07-14T09:22:47.789+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T09:22:47.823+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-07-14T09:22:41.570899+00:00 [queued]>
[2024-07-14T09:22:47.834+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-07-14T09:22:41.570899+00:00 [queued]>
[2024-07-14T09:22:47.835+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-14T09:22:47.853+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-07-14 09:22:41.570899+00:00
[2024-07-14T09:22:47.867+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=136) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T09:22:47.869+0000] {standard_task_runner.py:63} INFO - Started process 140 to run task
[2024-07-14T09:22:47.870+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2024-07-14T09:22:41.570899+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/python_dag.py', '--cfg-path', '/tmp/tmp4g84jhg6']
[2024-07-14T09:22:47.872+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask s3_upload
[2024-07-14T09:22:47.941+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-07-14T09:22:41.570899+00:00 [running]> on host 906654fcd818
[2024-07-14T09:22:48.058+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ademola Balogun' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T09:22:41.570899+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-14T09:22:41.570899+00:00'
[2024-07-14T09:22:48.060+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T09:22:48.095+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T09:22:48.099+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 8, in upload_s3_pipeline
    create_bucket_if_not_exists(s3, AWS_BUCKET_NAME)
                                    ^^^^^^^^^^^^^^^
NameError: name 'AWS_BUCKET_NAME' is not defined
[2024-07-14T09:22:48.117+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, run_id=manual__2024-07-14T09:22:41.570899+00:00, execution_date=20240714T092241, start_date=20240714T092247, end_date=20240714T092248
[2024-07-14T09:22:48.137+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task s3_upload (name 'AWS_BUCKET_NAME' is not defined; 140)
[2024-07-14T09:22:48.164+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-14T09:22:48.187+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T09:22:48.188+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
